# Generated by Django 3.0.5 on 2020-05-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_changed_image_field_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.CharField(max_length=100),
        ),
    ]
